### ISSUE TITLE
udp2raw-tunne

### ISSUE THREAD

**Issue by sxml** [binge8/op#1]
大佬 可不可以 自定义插件 可不可以增加第三方插件？

**Comment by binge8** [comment]
你想加什么？有源码吗？如果你会自己编译，也可以编译好自己安装

**Comment by sxml** [comment]
> 你想加什么？有源码吗？如果你会自己编译，也可以编译好自己安装
之前在F大群看你发的信息 x96找不到这个插件 不知道怎么搞 
https://github.com/sensec/luci-app-udp2raw/wiki/%E7%BC%96%E8%AF%91%E6%95%99%E7%A8%8B

https://github.com/sensec/openwrt-udp2raw
https://github.com/sensec/luci-app-udp2raw


https://github.com/WouldChar/openwrt-udp2raw-speeder

**Comment by sxml** [comment]
大佬请教下 是不是 bin.sh里 
#添加额外软件包
git clone https://github.com/sensec/luci-app-udp2raw.git
git clone https://github.com/sensec/openwrt-udp2raw.git

然后 actions 里 运行armv8稳定版  手动 再运行armv8打包 是吗？

**Comment by binge8** [comment]
> 大佬请教下 是不是 bin.sh里
> #添加额外软件包
> git clone https://github.com/sensec/luci-app-udp2raw.git
> git clone https://github.com/sensec/openwrt-udp2raw.git
> 
> 然后 actions 里 运行armv8稳定版 手动 再运行armv8打包 是吗？

添加软件包后面要跟上路径，比如我的：git clone https://github.com/sensec/luci-app-udp2raw.git package/openwrt-packages/luci-app-udp2raw
然后要在.config文件中选中，比如：CONFIG_PACKAGE_luci-app-udp2raw=y
然后编译>打包。 你会自己加那我就不加了，没多大用处
