### ISSUE TITLE
如何把snmp和acpi这两个组件编译进去呢？

### ISSUE THREAD

**Issue by y0823** [binge8/op#1]
因为在PVE虚拟机上安装，如果没有SNMP，做旁路由时，MAC地址会重复。而没有ACPI组件时，宿主机关机重启命令对OPENWRT不起效果。还有，如果要把PASSWALL编进去，是不是把PASSWALL前面的#去除，然后后面加上=y就行 了？真正的小白，虚心请教

**Comment by binge8** [comment]
会本地编译吗
