### ISSUE TITLE
运行几次都报错

### ISSUE THREAD

**Issue by sxml** [binge8/op#2]
FIRMWARE: /workdir/openwrt/bin/targets/armvirt/64
Error: Error 404: Not Found
？？？
我不懂 就增加这两条
bin.sh
#添加额外软件包
svn co https://github.com/sxml/mypackages/trunk/openwrt-udp2raw-speeder/udp2raw package/openwrt-packages/udp2raw

warmv8.config
CONFIG_PACKAGE_udp2raw=m

**Comment by binge8** [comment]
> FIRMWARE: /workdir/openwrt/bin/targets/armvirt/64
> Error: Error 404: Not Found
> ？？？
> 我不懂 就增加这两条
> bin.sh
> #添加额外软件包
> svn co /tmypackagesrunk/openwrt-udp2raw-speeder/udp2raw package/openwrt-packages/udp2raw
> 
> warmv8.config
> CONFIG_PACKAGE_udp2raw=m

很明显你这svn地址就是错误的

> FIRMWARE: /workdir/openwrt/bin/targets/armvirt/64
> Error: Error 404: Not Found
> ？？？
> 我不懂 就增加这两条
> bin.sh
> #添加额外软件包
> svn co https://github.com/sxml/mypackages/trunk/openwrt-udp2raw-speeder/udp2raw package/openwrt-packages/udp2raw
> 
> warmv8.config
> CONFIG_PACKAGE_udp2raw=m

很明显你这svn地址就是错误的
