### ISSUE TITLE
自动编译x64专业版时出现0s Run ncipollo/release-action@v1 Error: Error undefined: Parameter token or opts.auth is required

### ISSUE THREAD

**Issue by 626687360** [binge8/op#2]
自动编译x64专业版时出现0s Run ncipollo/release-action@v1 Error: Error undefined: Parameter token or opts.auth is required

**Comment by binge8** [comment]
ncipollo/release-action的问题去这里提交 https://github.com/ncipollo/release-action

**Comment by 626687360** [comment]
可是用的是你的代码失败的为什么要提交到那里

**Comment by 626687360** [comment]
我fork了以后没做任何修改这代码都编译不了啊

**Comment by binge8** [comment]
> 可是用的是你的代码失败的为什么要提交到那里

看来你是真不懂。第一，打个比方吧，大概意思就是我这个大工程里有若干个别人的小程序组合而成，这个报错就是其中一个小程序的错误，所以你要去找他。第二，人家小程序应该是没有问题的，我的每天自动编译，全部正常。我的代码不是全部照搬过去就能用的，人家这个小程序里token是必须要有的，至于token怎么搞的，去他那里找找教程
